### ISSUE TITLE
"red" region in velocity figure

### ISSUE THREAD

**Issue by ni-wei** [EvaBr/CFD-Lab#3]
For the "red" region in our velocity figure (near the top right corner, covering the upper half of the right boundary), e.g., from the DrivenCavity.10000.vtk in our repository, do we accept it as a reasonable phenomenon caused by the upper boundary condition, or shall we double check our other boundary conditions, say the right boundary, the left boundary, etc.?

![vel](https://cloud.githubusercontent.com/assets/6778307/7444709/4e1f7748-f191-11e4-9552-a5dae14544f5.png)

**Comment by ZhibinCH** [comment]
I think it would be the correct graph, as far as I understand, the right
boundary region is actually propagating the velocity(i.e. with time goes on
the red area is getting larger), because somehow the region is always the
first guy being touched by the coming fluid and then reflects, it results
in the "red".

2015-05-03 12:38 GMT+02:00 ni-wei notifications@github.com:

**Comment by EvaBr** [comment]
Hey, I would also think so, but as you may have noticed, we had a bug in our boundary condition (there was a minus missing), and also, we used abs instead of fabs for absolute value of doubles, which of course wasn't ok either.
After fixing these two things, the results we get are the same as the officially given output. :smiley:

**Comment by ni-wei** [comment]
Closing it. Thanks for the discussion!
